-- ============================================================================
-- Friends v2. Row Level Security
-- Run after 02_functions.sql.
--
-- v1's mistake was `using (true)`, which meant anyone holding the anon key
-- (it ships in the JS bundle, it is public by definition) could read and
-- write every group's data. The rule below is absolute: there is no
-- `using (true)` anywhere in this file, and every policy resolves to either
-- "this row is mine" or "I am a member of the group this row belongs to".
-- ============================================================================

alter table profiles           enable row level security;
alter table groups             enable row level security;
alter table group_members      enable row level security;
alter table cycles             enable row level security;
alter table goals              enable row level security;
alter table checkins           enable row level security;
alter table checkin_items      enable row level security;
alter table away_periods       enable row level security;
alter table nudges             enable row level security;
alter table notifications_log  enable row level security;

-- Helper: do I share at least one group with this person? Used only by the
-- profiles policy. SECURITY DEFINER for the same anti-recursion reason as
-- is_member(), the lookup itself must not be filtered by RLS.
create or replace function shares_group(other uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from group_members mine
    join group_members theirs on theirs.group_id = mine.group_id
    where mine.user_id = auth.uid() and theirs.user_id = other
  );
$$;

-- ---------------------------------------------------------------------------
-- profiles
-- Enforces: you can see yourself, and you can see people you actually share a
-- group with. Names and avatars of strangers stay invisible; you can only
-- edit your own row.
-- ---------------------------------------------------------------------------
drop policy if exists profiles_select on profiles;
create policy profiles_select on profiles for select to authenticated
  using (id = auth.uid() or shares_group(id));

drop policy if exists profiles_insert on profiles;
create policy profiles_insert on profiles for insert to authenticated
  with check (id = auth.uid());

drop policy if exists profiles_update on profiles;
create policy profiles_update on profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- ---------------------------------------------------------------------------
-- groups
-- Enforces: a group is invisible until you are in it. Note there is no INSERT
-- policy at all, creation goes exclusively through create_group(), so an
-- attacker cannot mint a group with a chosen invite_code to squat on. Only
-- admins can change the check-in rhythm, because changing it moves the ritual
-- for everyone.
-- ---------------------------------------------------------------------------
drop policy if exists groups_select on groups;
create policy groups_select on groups for select to authenticated
  using (is_member(id));

drop policy if exists groups_update on groups;
create policy groups_update on groups for update to authenticated
  using (is_group_admin(id)) with check (is_group_admin(id));

-- ---------------------------------------------------------------------------
-- group_members
-- Enforces: you see the roster of your own groups only. This is the table
-- that makes is_member() necessary, a policy here that queried
-- group_members directly would recurse forever. Joining goes through
-- join_group() (no INSERT policy); you may remove yourself, and an admin may
-- remove anyone.
-- ---------------------------------------------------------------------------
drop policy if exists group_members_select on group_members;
create policy group_members_select on group_members for select to authenticated
  using (is_member(group_id));

drop policy if exists group_members_delete on group_members;
create policy group_members_delete on group_members for delete to authenticated
  using (user_id = auth.uid() or is_group_admin(group_id));

-- ---------------------------------------------------------------------------
-- cycles
-- Enforces: read-only to members. Cycles are generated by ensure_cycles() and
-- advanced by tick(); no client may invent, move or delete a period, which
-- would otherwise be a trivial way to erase a missed check-in from history.
-- ---------------------------------------------------------------------------
drop policy if exists cycles_select on cycles;
create policy cycles_select on cycles for select to authenticated
  using (is_member(group_id));

-- ---------------------------------------------------------------------------
-- goals
-- Enforces: members read every goal in the group (accountability requires
-- visibility). You may create a personal goal only for yourself; group goals
-- are unowned and any member may create one. Editing follows the same split,
-- with admins able to tidy up. Deleting is deliberately narrow, the intended
-- exit from a goal is status='paused' or 'abandoned', which keeps the history
-- intact rather than rewriting it.
-- ---------------------------------------------------------------------------
drop policy if exists goals_select on goals;
create policy goals_select on goals for select to authenticated
  using (is_member(group_id));

drop policy if exists goals_insert on goals;
create policy goals_insert on goals for insert to authenticated
  with check (
    is_member(group_id)
    and (
      (kind = 'personal' and owner_id = auth.uid())
      or (kind = 'group' and owner_id is null)
    )
  );

drop policy if exists goals_update on goals;
create policy goals_update on goals for update to authenticated
  using (
    is_member(group_id)
    and (owner_id = auth.uid() or (kind = 'group' and owner_id is null))
  )
  with check (
    is_member(group_id)
    and (owner_id = auth.uid() or (kind = 'group' and owner_id is null))
  );

drop policy if exists goals_delete on goals;
create policy goals_delete on goals for delete to authenticated
  using (owner_id = auth.uid() or is_group_admin(group_id));

-- ---------------------------------------------------------------------------
-- checkins
-- Enforces: members read every check-in in the group; you may only write your
-- own, and only into a cycle that has actually opened.
--
-- The 12-hour tail on closes_at is the offline allowance: a check-in composed
-- on the train inside the window must still sync when the phone reconnects an
-- hour after close. It is bounded so history cannot be rewritten days later.
-- There is no UPDATE-by-others and no DELETE policy, nobody can quietly
-- retract or edit someone else's record of what happened.
-- ---------------------------------------------------------------------------
drop policy if exists checkins_select on checkins;
create policy checkins_select on checkins for select to authenticated
  using (exists (
    select 1 from cycles c where c.id = cycle_id and is_member(c.group_id)
  ));

drop policy if exists checkins_insert on checkins;
create policy checkins_insert on checkins for insert to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from cycles c
      where c.id = cycle_id
        and is_member(c.group_id)
        and c.opens_at <= now()
        and c.closes_at > now() - interval '12 hours'
    )
  );

drop policy if exists checkins_update on checkins;
create policy checkins_update on checkins for update to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from cycles c
      where c.id = cycle_id
        and c.opens_at <= now()
        and c.closes_at > now() - interval '12 hours'
    )
  );

-- ---------------------------------------------------------------------------
-- checkin_items
-- Enforces: visibility is inherited from the parent check-in. Writing an item
-- requires owning that check-in AND the goal being in the same group as the
-- check-in's cycle.
--
-- That second half is not redundant. Owning the check-in only says which row
-- the item hangs off; goal_id was a separate, unchecked pointer, so a member
-- of one group could attach another group's goal to their own check-in. It
-- leaked nothing on its own (reads stay gated) but it wrote a row that
-- crosses a tenant boundary, and anything that later aggregates by goal_id
-- would pick it up. It was also an existence oracle: a real-but-invisible
-- goal id succeeded while a made-up one failed on the foreign key, which
-- distinguishes "this UUID is a goal somewhere" from "it is not". With the
-- group check in place both now fail identically, before the FK is reached.
-- ---------------------------------------------------------------------------
drop policy if exists checkin_items_select on checkin_items;
create policy checkin_items_select on checkin_items for select to authenticated
  using (exists (
    select 1 from checkins ck join cycles c on c.id = ck.cycle_id
    where ck.id = checkin_id and is_member(c.group_id)
  ));

drop policy if exists checkin_items_write on checkin_items;
create policy checkin_items_write on checkin_items for all to authenticated
  using (exists (
    select 1 from checkins ck
    where ck.id = checkin_items.checkin_id and ck.user_id = auth.uid()
  ))
  with check (exists (
    select 1
    from checkins ck
    join cycles c on c.id = ck.cycle_id
    join goals  g on g.id = checkin_items.goal_id
    where ck.id = checkin_items.checkin_id
      and ck.user_id = auth.uid()
      and g.group_id = c.group_id
  ));

-- ---------------------------------------------------------------------------
-- away_periods
-- Enforces: the group can see that you are away (that is the entire point. -- declared absence reads differently from silence), but only you can declare
-- or withdraw it, and only for a cycle in a group you belong to.
-- ---------------------------------------------------------------------------
drop policy if exists away_select on away_periods;
create policy away_select on away_periods for select to authenticated
  using (exists (
    select 1 from cycles c where c.id = cycle_id and is_member(c.group_id)
  ));

drop policy if exists away_write on away_periods;
create policy away_write on away_periods for all to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from cycles c where c.id = cycle_id and is_member(c.group_id)
    )
  );

-- ---------------------------------------------------------------------------
-- nudges
-- Enforces: the whole group sees that someone has gone quiet, which is what
-- lets a nudge be claimed rather than assigned. Nudges are created only by
-- tick() (no INSERT policy) so they cannot be fabricated, and the subject of
-- a nudge cannot close their own, otherwise the quiet person could dismiss
-- the one mechanism designed to reach them.
-- ---------------------------------------------------------------------------
drop policy if exists nudges_select on nudges;
create policy nudges_select on nudges for select to authenticated
  using (is_member(group_id));

drop policy if exists nudges_update on nudges;
create policy nudges_update on nudges for update to authenticated
  using (is_member(group_id) and subject_id <> auth.uid())
  with check (is_member(group_id) and subject_id <> auth.uid());

-- ---------------------------------------------------------------------------
-- notifications_log
-- Enforces: you can audit what the app sent you and nothing else. There is no
-- write policy, only the Edge Function's service-role key inserts here, which
-- is what makes the row a reliable "already sent" lock and keeps the two-email
-- ceiling honest even if the sender runs twice.
-- ---------------------------------------------------------------------------
drop policy if exists notifications_select on notifications_log;
create policy notifications_select on notifications_log for select to authenticated
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Execution grants.
--
-- PostgreSQL grants EXECUTE on every new function to PUBLIC, and both `anon`
-- and `authenticated` inherit from PUBLIC. So `revoke ... from authenticated`
-- is a no-op, the earlier version of this file did exactly that for
-- ensure_cycles() and left it callable by anyone holding the anon key. Every
-- function has to be revoked from PUBLIC first, then granted back by name.
--
-- Named one at a time rather than `revoke ... on all functions in schema
-- public`: that would also strip gen_random_uuid(), which column DEFAULTs
-- execute as the *inserting* user, breaking every insert.
-- ---------------------------------------------------------------------------
revoke execute on function
  is_member(uuid), is_group_admin(uuid), shares_group(uuid),
  missed_cycle(uuid, uuid), ensure_cycles(uuid, int), handle_new_user(),
  ensure_profile(),
  create_group(text, text, int, int, int, int), join_group(text),
  submit_checkin(uuid, text, text, jsonb, text), claim_nudge(uuid), tick()
  from public;

-- The three membership helpers are called from inside policy expressions,
-- which are evaluated as the querying role, so they need EXECUTE even though
-- no client calls them directly.
grant execute on function is_member(uuid), is_group_admin(uuid), shares_group(uuid)
  to authenticated;

grant execute on function create_group(text, text, int, int, int, int) to authenticated;
grant execute on function join_group(text)                              to authenticated;
grant execute on function submit_checkin(uuid, text, text, jsonb, text) to authenticated;
grant execute on function claim_nudge(uuid)                             to authenticated;

-- tick() stays callable by a signed-in user: it is idempotent, and letting
-- the client call it on app open means a group keeps ticking even before
-- pg_cron is configured. It is NOT granted to anon, it is a SECURITY DEFINER
-- function that writes, and an unauthenticated caller has no business
-- driving it.
grant execute on function tick() to authenticated;

-- ensure_cycles() and missed_cycle() get no grant at all. Both are internal
-- helpers reached through SECURITY DEFINER callers, and both took a
-- caller-supplied id for a group or a person the caller need not belong to:
-- missed_cycle('someone else', 'a cycle in a group you are not in') answered
-- honestly, and ensure_cycles(any group, 5000) would have written thousands
-- of rows into a stranger's group.
--
-- handle_new_user() is a trigger function; EXECUTE is checked when the
-- trigger is created, not when it fires, so revoking it changes nothing at
-- run time and removes it as a directly callable entry point.
