import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useT } from '../lib/i18n'
import { loadCelebrations } from '../lib/celebrations'
import { Avatar, Section } from './ui'
import Confetti from './Confetti'

/**
 * What the group did, and did not do, said once and quietly.
 *
 * Every row here is generated by tick() when a day closes, never by a client.
 * That matters for how it reads: nobody reports anybody. The app noticed the
 * day ended and wrote down what was outstanding, which is a different social
 * act from a person filing a complaint about their friend.
 *
 * Birthdays are the second kind of row, written by record_birthdays in
 * supabase/20_quiet_and_birthdays.sql. They live here rather than in a banner
 * of their own for a reason worth stating: this is the only place in the app
 * that says anything about a person that is not about their performance, and a
 * feed of nothing but missed goals is one people learn to dread. The year is
 * never sent to the client and never shown.
 *
 * Somebody who marked themselves away is never in here. That exclusion lives
 * in record_missed_goals rather than in this component, so there is exactly
 * one definition of what counts as a miss and no way for the display to drift
 * from it.
 *
 * Deliberately not styled as an alert. No red, no warning icon, no count
 * badge. A daily cadence generates these constantly, and a feed that treats
 * every ordinary human gap as an incident is one people learn to stop reading.
 *
 * CELEBRATIONS ARE THE THIRD KIND, AND THE ONLY ONE A PERSON WRITES.
 *
 * They come from their own table rather than from a new `kind` on group_feed,
 * because group_feed is readable by the group and writable by nobody, which is
 * a property worth keeping exactly as it is. Two reads merged by time here,
 * which costs one request and keeps that invariant intact.
 *
 * They are also the one row here that gets a card of its own. The misses and
 * the birthdays are lines in a list on purpose, easy to skim and easy to skip;
 * a celebration is the thing on this page most worth stopping at, and it is
 * the only place in the app where the visual weight is allowed to go up.
 */
export default function GroupFeed({ groupId, limit = 12 }) {
  const { t } = useT()
  const [rows, setRows] = useState([])
  const [missing, setMissing] = useState(false)

  const load = useCallback(async () => {
    if (!groupId) return
    try {
      /* Both in flight at once. A celebration failing because 25 has not been
         run must not cost the misses and the birthdays, and vice versa. */
      const [feed, party] = await Promise.all([
        supabase
          .from('group_feed_detail')
          .select('id, user_id, kind, goal_title, display_name, avatar_url, created_at')
          .eq('group_id', groupId)
          .order('created_at', { ascending: false })
          .limit(limit),
        loadCelebrations(groupId, limit).catch(() => ({ rows: [], missing: true })),
      ])

      if (feed.error) {
        /* The view arrives with 18_daily_roles_and_feed.sql. Until that has
           been run this section is simply absent, rather than an error about
           a relation nobody reading the board has heard of. */
        const raw = `${feed.error.code ?? ''} ${feed.error.message ?? ''}`.toLowerCase()
        setMissing(
          raw.includes('pgrst205') || raw.includes('42p01') || raw.includes('schema cache'),
        )
      } else {
        setMissing(false)
      }

      const merged = [
        ...(feed.data ?? []),
        ...party.rows.map((c) => ({
          id: `celebration-${c.id}`,
          kind: 'celebration',
          created_at: c.created_at,
          display_name: c.sender_name,
          avatar_url: c.sender_avatar,
          receiver_name: c.receiver_name,
          receiver_avatar: c.receiver_avatar,
          self: c.sender_id === c.receiver_id,
          message: c.message,
        })),
      ]
        .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
        .slice(0, limit)

      setRows(merged)
    } catch {
      /* Offline. Leave whatever is already on screen. */
    }
  }, [groupId, limit])

  useEffect(() => {
    load()
  }, [load])

  /* Refetched when the tab comes back, because these rows are written by a
     scheduled job rather than by anything happening in this browser. */
  useEffect(() => {
    const onWake = () => document.visibilityState === 'visible' && load()
    document.addEventListener('visibilitychange', onWake)
    return () => document.removeEventListener('visibilitychange', onWake)
  }, [load])

  /* `missing` is only about the feed view. A group with no feed but a
     celebration in it still has something to say. */
  if (rows.length === 0) return null

  return (
    <Section title={t('board.feed')}>
      <div className="lg px-5">
        <div className="list">
        {rows.map((r) => {
          const birthday = r.kind === 'birthday'

          if (r.kind === 'celebration') {
            return (
              <div key={r.id} className="py-3">
                <div className="lg relative overflow-hidden p-4">
                  <Confetti />
                  <div className="relative flex items-start gap-3.5">
                    <Avatar
                      profile={{ display_name: r.display_name, avatar_url: r.avatar_url }}
                      size={32}
                    />
                    <div className="min-w-0 flex-1">
                      <p className="text-label font-bold uppercase tracking-[0.06em] text-muted">
                        {/* Somebody celebrating themselves gets its own line.
                            "Rue on Rue" reads as a bug in the join rather than
                            as a person being pleased with their own week. */}
                        {r.self
                          ? t('celebrate.feed_self', { name: r.display_name ?? '' })
                          : t('celebrate.feed_from', {
                              name: r.display_name ?? '',
                              about: r.receiver_name ?? '',
                            })}
                      </p>
                      <p className="mt-1.5 text-small leading-snug text-ink">{r.message}</p>
                    </div>
                  </div>
                </div>
              </div>
            )
          }

          return (
            <div key={r.id} className="flex items-start gap-3.5 py-4">
              <Avatar
                profile={{ display_name: r.display_name, avatar_url: r.avatar_url }}
                size={32}
              />
              {/* Full ink for a birthday, muted for a miss. The one line here
                  worth reading twice should not be the same weight as the one
                  that is deliberately easy to skip. */}
              <p
                className={`min-w-0 flex-1 text-small leading-snug ${
                  birthday ? 'text-ink' : 'text-muted'
                }`}
              >
                {birthday
                  ? t('board.birthday_line', { name: r.display_name ?? '' })
                  : t('board.missed_line', {
                      name: r.display_name ?? '',
                      goal: r.goal_title ?? '',
                    })}
              </p>
            </div>
          )
        })}
        </div>
      </div>
    </Section>
  )
}
