import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useT } from '../lib/i18n'
import { Avatar, Section } from './ui'

/**
 * What the group did not do, said once and quietly.
 *
 * Every row here is generated by tick() when a day closes, never by a client.
 * That matters for how it reads: nobody reports anybody. The app noticed the
 * day ended and wrote down what was outstanding, which is a different social
 * act from a person filing a complaint about their friend.
 *
 * Somebody who marked themselves away is never in here. That exclusion lives
 * in record_missed_goals rather than in this component, so there is exactly
 * one definition of what counts as a miss and no way for the display to drift
 * from it.
 *
 * Deliberately not styled as an alert. No red, no warning icon, no count
 * badge. A daily cadence generates these constantly, and a feed that treats
 * every ordinary human gap as an incident is one people learn to stop reading.
 */
export default function GroupFeed({ groupId, limit = 12 }) {
  const { t } = useT()
  const [rows, setRows] = useState([])
  const [missing, setMissing] = useState(false)

  const load = useCallback(async () => {
    if (!groupId) return
    try {
      const { data, error } = await supabase
        .from('group_feed_detail')
        .select('id, user_id, kind, goal_title, display_name, avatar_url, created_at')
        .eq('group_id', groupId)
        .order('created_at', { ascending: false })
        .limit(limit)

      if (error) {
        /* The view arrives with 18_daily_roles_and_feed.sql. Until that has
           been run this section is simply absent, rather than an error about
           a relation nobody reading the board has heard of. */
        const raw = `${error.code ?? ''} ${error.message ?? ''}`.toLowerCase()
        setMissing(
          raw.includes('pgrst205') || raw.includes('42p01') || raw.includes('schema cache'),
        )
        return
      }
      setMissing(false)
      setRows(data ?? [])
    } catch {
      /* Offline. Leave whatever is already on screen. */
    }
  }, [groupId, limit])

  useEffect(() => {
    load()
  }, [load])

  /* Refetched when the tab comes back, because these rows are written by a
     scheduled job rather than by anything happening in this browser. */
  useEffect(() => {
    const onWake = () => document.visibilityState === 'visible' && load()
    document.addEventListener('visibilitychange', onWake)
    return () => document.removeEventListener('visibilitychange', onWake)
  }, [load])

  if (missing || rows.length === 0) return null

  return (
    <Section title={t('board.feed')}>
      <div className="list">
        {rows.map((r) => (
          <div key={r.id} className="flex items-start gap-3.5 py-4">
            <Avatar
              profile={{ display_name: r.display_name, avatar_url: r.avatar_url }}
              size={32}
            />
            <p className="min-w-0 flex-1 text-small leading-snug text-muted">
              {t('board.missed_line', {
                name: r.display_name ?? '',
                goal: r.goal_title ?? '',
              })}
            </p>
          </div>
        ))}
      </div>
    </Section>
  )
}
