/**
 * node scripts/sitemap.mjs   (or: npm run sitemap)
 *
 * Writes public/sitemap.xml from the router's own idea of what is public.
 *
 * Hand-maintained sitemaps drift, and this one had: it listed seven URLs and
 * missed the three legal pages, which are public, linked from every footer,
 * and the only pages on the site anybody is ever required to read. It also
 * carried no lastmod, which is the one hint Google uses to decide whether a
 * recrawl is worth it.
 *
 * The chapter slugs are read out of src/content/previews.js rather than
 * imported, because that file imports from the app and this script has to run
 * under plain node with no bundler, exactly like the tests do.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { ORIGIN, canonicalPath, isPrivate, sitemapPaths } from '../src/lib/seo.js'

const slugs = [...readFileSync('src/content/previews.js', 'utf8').matchAll(/slug: '([a-z-]+)'/g)].map(
  (m) => m[1],
)

if (slugs.length === 0) {
  console.error('No chapter slugs found in src/content/previews.js. Refusing to write a sitemap that silently lost the books.')
  process.exit(1)
}

const paths = sitemapPaths(slugs)

/* The two rules a sitemap must not break: nothing private, and every entry
   its own canonical. Both are asserted rather than assumed, because a sitemap
   that disagrees with the pages it lists is worse than no sitemap. */
const leaked = paths.filter(isPrivate)
if (leaked.length) {
  console.error('Private paths in the sitemap:', leaked.join(', '))
  process.exit(1)
}
const aliased = paths.filter((p) => canonicalPath(p) !== p)
if (aliased.length) {
  console.error('Non-canonical paths in the sitemap:', aliased.join(', '))
  process.exit(1)
}

const today = new Date().toISOString().slice(0, 10)

const priority = (p) => {
  if (p === '/') return '1.0'
  if (p.startsWith('/books/')) return '0.9'
  if (p.startsWith('/legal/')) return '0.3'
  return '0.8'
}

const urls = paths
  .map(
    (p) =>
      `  <url><loc>${ORIGIN}${p}</loc><lastmod>${today}</lastmod><changefreq>monthly</changefreq><priority>${priority(p)}</priority></url>`,
  )
  .join('\n')

writeFileSync(
  'public/sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/sitemap.mjs. Do not edit by hand: run \`npm run sitemap\`.

  Every entry is its own canonical, and the script refuses to write the file
  if that stops being true. The aliases /library and /lectures are absent on
  purpose: they render the same chapters as /books and now say so in a
  canonical tag, so listing them would ask Google to crawl three copies of
  one page and then discard two.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`,
)

console.log(`public/sitemap.xml: ${paths.length} urls, ${slugs.length} chapters, lastmod ${today}`)
